version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${HOST_PORT}:${NGINX_PORT}
    env_file:
    - .env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  express-app:
    depends_on:
      - mongo-db
      - redis-db

  mongo-db:
    image: mongo
    volumes:
      - mymongo-db:/data/db

  redis-db:
    image: redis

volumes:
  mymongo-db: