version: '3'
services:
  express-app:
    build: 
      args:
        - APP_ENV=development
      context: .
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev

  mongo-db:
    env_file:
      - .env